name: Go

on:
  push:
    branches: [ feature/*, main ]
  pull_request:
    branches: [ main, /^release-.*$/ ]

jobs:
  test-onprem-runner:
    runs-on: itk8s-svldev-2-runner
    steps:
    - name: test list dirs
      run: whoami
      shell: bash
    
  go-tests:
    runs-on: itk8s-svldev-2-runner
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Run
      run: go run main.go
      env:
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
